targets:
  $default:
    sources:
      - lib/**
      - graphql/**
      - pubspec.yaml
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphql/schema.graphql
              queries_glob: lib/graphql/*/*.graphql
              output: lib/graphql/models/schema.dart
              naming_scheme: pathedWithFields
          scalar_mapping:
            - custom_parser_import: 'package:uuid/uuid.dart'
            - graphql_type: UUID
              dart_type: String # 或者 Uuid，根据你的需求
            - graphql_type: Decimal
              dart_type: double # 或者 String，取决于你的需求
            - graphql_type: DateTime
              dart_type: DateTime
            - graphql_type: Date
              dart_type: DateTime
            - graphql_type: JSON
              dart_type: Map<String, dynamic> # 或者 String，取决于你的需求